language: java
jdk:
  - oraclejdk8
install:
  - echo "<settings><servers><server><id>mulesoft-private</id><username>\${env.MULE_USER}</username><password>\${env.MULE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn install --settings ~/settings.xml
